#!/bin/bash
OYAPI=/home/pi/github/oyapi

pushd $OYAPI

sudo -u pi mkdir -p local/logs
TS=`date +%Y%m%d.%H%M%S`
LOGFILE="${OYAPI}/local/logs/oyapi-${TS}.log"
rm -f "${OYAPI}/local/oyapi.log"
sudo -u pi ln -sf ${LOGFILE} "${OYAPI}/local/oyapi.log"

npm start 2>&1 | tee -a ${LOGFILE}
