#!/bin/bash
OYAPI=/home/pi/github/oyapi

pushd $OYAPI

sudo -u pi mkdir -p logs
TS=`date +%Y%m%d.%H%M%S`
LOGFILE="${OYAPI}/logs/oyapi-${TS}.log"
rm -f "${OYAPI}/oyapi.log"
sudo -u pi ln -sf ${LOGFILE} "${OYAPI}/oyapi.log"

npm start 2>&1 | tee -a ${LOGFILE}
