#!/bin/bash

if [ ! -e /etc/rc2.d/S50oyapi ]; then
    while true; do
        echo -e "UPDATE\t: Oyapi currently needs to be started manually"
        read -p "UPDATE  : Configure system to launch Oyapi automatically on power-up? [y,n]:" LAUNCH
        case $LAUNCH in
            [y]* ) break;;
            [n]* ) break;;
               * ) echo "        : Please enter 'y' or 'n'";;
        esac
    done
    if [ "$LAUNCH" == "y" ]; then
        echo -e "UPDATE\t: sudo ln -s `pwd`/scripts/oyapi /etc/rc2.d/S50oyapi"
        sudo cp scripts/oyapi /etc/init.d
        sudo ln -s /etc/init.d/oyapi /etc/rc2.d/S50oyapi
        sync
    fi
fi

echo -e "UPDATE\t: Retrieving latest github content..."
git pull
RC=$?; if [ "$RC" != "0" ]; then 
    echo -e "ERROR\t: Could not update"
    exit $RC
fi
sync

echo -e "UPDATE\t: Installing dependencies..."
npm install
sync

echo -e "UPDATE\t: Building web server..."
npm run build
sync

