#!/bin/bash

if [ ! -e /etc/rc2.d/S50oyapi ]; then
    while true; do
        read -p "UPDATE : Launch web server on power-up [y,n]:" LAUNCH
        case $LAUNCH in
            [y]* ) break;;
            [n]* ) break;;
               * ) echo "        : Please enter 'y' or 'n';;
        esac
    done
    if [ "$LAUNCH" == "y" ]; then
        echo -e "UPDATE\t: sudo ln -s `pwd`/scripts/oyapi /etc/rc2.d/S50oyapi"
        sudo ln -s `pwd`/scripts/oyapi /etc/rc2.d/S50oyapi
    fi
fi

echo -e "UPDATE\t: Retrieving latest github content..."
git pull
echo -e "UPDATE\t: Installing dependencies..."
npm install
echo -e "UPDATE\t: Building web server..."
npm run build

